const CORE='adaptive-study-v3-25-3-core';
const RUNTIME='adaptive-study-v3-25-3-runtime';
const COURSE='adaptive-course-v3-25-3';
const PAGES='adaptive-pages-v3-25-3';
const MEDIA='adaptive-media-v3-25-3';
const CORE_ASSETS=["./index.html?build=3253","./styles.css","./content.js?build=3253","./original_corpus.js?build=3253","./exercises.js?build=3253","./app.js?build=3253","./manifest.webmanifest"];
async function cacheMany(name,urls,workers=8){const c=await caches.open(name);let i=0;async function w(){while(i<urls.length){const u=urls[i++];try{const r=await fetch(u,{cache:'reload'});if(r.ok)await c.put(u,r.clone());}catch(e){}}}await Promise.all(Array.from({length:Math.min(workers,urls.length||1)},w));}
self.addEventListener('install',e=>{e.waitUntil(cacheMany(CORE,CORE_ASSETS,4).then(()=>self.skipWaiting()));});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>(/^(adaptive-study|adaptive-course|adaptive-pages|adaptive-media|adaptive-v)/.test(k))&&![CORE,RUNTIME,COURSE,PAGES,MEDIA].includes(k)).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));});
async function networkFirst(req,cacheName){try{const r=await fetch(req,{cache:'no-store'});if(r&&r.ok){const c=await caches.open(cacheName);c.put(req,r.clone());}return r;}catch(e){return (await caches.match(req))||Response.error();}}
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url),p=u.pathname.toLowerCase();if(e.request.mode==='navigate'||p.endsWith('/app.js')||p.endsWith('/content.js')||p.endsWith('/exercises.js')||p.endsWith('/styles.css')||p.endsWith('/index.html')){e.respondWith(networkFirst(e.request,RUNTIME));return;}if(u.pathname.includes('/assets/quiz_media/')&&p.endsWith('.webp')){e.respondWith(caches.match(e.request).then(r=>r||networkFirst(e.request,MEDIA)));return;}if(u.pathname.includes('/assets/course_pages/')&&(p.endsWith('.webp')||p.endsWith('.jpg')||p.endsWith('.jpeg'))){e.respondWith(caches.match(e.request).then(r=>r||networkFirst(e.request,PAGES)));return;}if(p.endsWith('.pdf')){e.respondWith(caches.match(e.request).then(r=>r||networkFirst(e.request,COURSE)));return;}e.respondWith(caches.match(e.request).then(r=>r||networkFirst(e.request,RUNTIME)));});