plugins {
    id 'com.android.application'
}

android {
    namespace 'com.azrazieliz.adaptivestudy'
    compileSdk 35

    defaultConfig {
        applicationId 'com.azrazieliz.adaptivestudy'
        minSdk 26
        targetSdk 35
        versionCode 3260
        versionName '3.26.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
